export const products = [
  {
    id: "p001",
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with USB receiver",
    price: 599.99,
    category: "Electronics",
    brand: "LogiTech",
    stock: 120,
    rating: 4.5,
    isAvailable: true,
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "p002",
    name: "Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with blue switches",
    price: 2499.0,
    category: "Electronics",
    brand: "KeyChron",
    stock: 80,
    rating: 4.7,
    isAvailable: true,
    createdAt: "2026-04-02T12:30:00Z",
  },
  {
    id: "p003",
    name: "Running Shoes",
    description: "Lightweight running shoes for daily workouts",
    price: 1799.5,
    category: "Footwear",
    brand: "Nike",
    stock: 60,
    rating: 4.3,
    isAvailable: true,
    createdAt: "2026-04-03T09:15:00Z",
  },
  {
    id: "p004",
    name: "Bluetooth Headphones",
    description: "Noise-cancelling over-ear headphones",
    price: 3499.99,
    category: "Electronics",
    brand: "Sony",
    stock: 45,
    rating: 4.6,
    isAvailable: true,
    createdAt: "2026-04-04T14:45:00Z",
  },
  {
    id: "p005",
    name: "Coffee Mug",
    description: "Ceramic coffee mug with 350ml capacity",
    price: 199.0,
    category: "Home & Kitchen",
    brand: "HomeEssentials",
    stock: 200,
    rating: 4.2,
    isAvailable: true,
    createdAt: "2026-04-05T08:20:00Z",
  },
  {
    id: "p006",
    name: "Smartphone",
    description: "6.5-inch display, 128GB storage, 5G enabled",
    price: 15999.0,
    category: "Electronics",
    brand: "Samsung",
    stock: 30,
    rating: 4.4,
    isAvailable: true,
    createdAt: "2026-04-06T11:10:00Z",
  },
  {
    id: "p007",
    name: "Backpack",
    description: "Water-resistant backpack with laptop compartment",
    price: 899.0,
    category: "Accessories",
    brand: "Skybags",
    stock: 75,
    rating: 4.1,
    isAvailable: true,
    createdAt: "2026-04-07T16:00:00Z",
  },
];
