services:
  my-db:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager # make sure the db always runs on manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 5s
        order: stop-first
      rollback_config:
        parallelism: 1
        order: stop-first
    environment:
      POSTGRES_USER: db_admin_user
      POSTGRES_DB: my_swarm_db
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password # this tells swarm to take this db_password  and save to the container in encrypted formate safely inside /run/secrets/db_password
    networks:
      - database_net
    volumes:
      - my-postgres-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin_user -d my_swarm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  my-db-backup:
    image: prodrigestivill/postgres-backup-local:16-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_HOST=my-db
      - POSTGRES_DB=my_swarm_db
      - POSTGRES_USER=db_admin_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_ON_START=TRUE
    secrets:
      - db_password
    networks:
      - database_net
    volumes:
      - /home/ubuntu/postgres-stack/backups:/backups

secrets:
  db_password:
    file: ./db_password.txt # this will load the password securely into db_password from file and swarm can use that in particular service where it is needed.
volumes:
  my-postgres-vol:
networks:
  database_net:
    driver: overlay
