name: "Bloggy app"
on:
  push:
    branches: ["master"]
    paths:
      # This path filter ensures the pipeline only triggers when files inside this specific folder changes.
      - "week-14.1(CI-CD)/**"
  pull_request:
    branches: ["master"]
    paths:
      - "week-14.1(CI-CD)/**"
# ADDED THIS: This tells EVERY job below to run their commands
# inside your specific project directory. Without this, your scripts fail!
defaults:
  run:
    working-directory: "week-14.1(CI-CD)"
jobs:
  # ==========================================
  # JOB 1: CODE QUALITY CHECK (LINT)
  # ==========================================
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] #run lint for all the given node version
    steps:
      # CRITICAL: Because this is a brand new, isolated virtual machine,
      # we MUST check out the code and set up Node all over again.
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          # CACHE: Tells GitHub to store your downloaded 'node_modules' directory in its secure cloud storage.
          # On future runs, it restores these modules instantly rather than downloading them over the internet.
          cache: npm
          # CACHE DEPENDENCY PATH: Tells GitHub where your 'package-lock.json' file is located.
          # GitHub creates a unique signature (hash) of this file. If the file doesn't change, it reuses the cache.
          # If you install a new package, this file changes, and GitHub knows to bypass the cache and do a fresh install.
          cache-dependency-path: "week-14.1(CI-CD)/package-lock.json"
      - name: Install dep
        run: npm ci
      - name: Run Linter 🔍
        run: npm run lint

  # ==========================================
  # JOB 2: AUTOMATED TESTING
  # ==========================================
  test:
    runs-on: ubuntu-latest
    # DEPENDENCY: Runs in parallel with the other job but after lint is successfully completed.
    needs: lint
    steps:
      # Spin up the environment fresh for testing
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm # Restores dependencies instantly from the shared cache
          cache-dependency-path: "week-14.1(CI-CD)/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Run Tests 🧪
        run: npm run test

  # ==========================================
  # JOB 3: PRODUCTION COMPILATION (BUILD)
  # ==========================================
  build:
    runs-on: ubuntu-latest
    steps:
      # Spin up the environment fresh for the build step
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: "week-14.1(CI-CD)/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Build app 🏗️
        run: npm run build

  # ========================================
  # JOB 4: BUILD & PUSH TO REGISTRY (Continuous Delivery - Docker hub)
  # ========================================
  build-and-push:
    runs-on: ubuntu-latest
    needs: [lint, test, build] # makes sure all the jobs runs successfuly before running this one
    steps:
      - name: checkout the source code # checkout the source code to VM machine
        uses: actions/checkout@v4
      - name: login to docker hub # we will use github secret to login to docker hub so that we can push the image
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push to Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./week-14.1(CI-CD)
          files: ./week-14.1(CI-CD)/Dockerfile
          push: true
          platforms: linux/amd64
          # tags: ${{secrets.DOCKERHUB_USERNAME}}/bloggy-app:${{ github.ref_name }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/bloggy-app:latest
